### ISSUE TITLE
Adding review form to existing assignment

### ISSUE THREAD

**Issue by kongebra** [JohanAanesen/NTNU-Bachelor-Management-System-For-CS-Assignments#36]
### Environment
Only running webservice, localhost. Not Docker.

### What I did
Created a review form called "Test", and 2 text fields: "A" & "B"
Edit Assignment 1, adding the review form to it.
Press update button, got this message

### Error
```
2019/03/07 21:59:49 The HTTP request to schedulerservice failed with error Get http:///1/1: http: no Host in request URL
2019/03/07 21:59:49 Post http:: http: no Host in request URL
```

**Comment by JohanAanesen** [comment]
This is because when you update or create an assignment with the peer review nr set and a submission form set, it will try and schedule the peer review with the schedulerservice. Since you are not running this through docker it won't get the envvar which holds the address to the service, even with an address you are not runnning the service:

How to fix this:
- See docker-compose.yml for the name of the envvar
- Run scheduleservice locally
- Set it locally in your environment as SCHEDULE_SERVICE: localhost:8086
